# Describes the format for available light services

handle_event:
  description: Request handling of an event.
  fields:
    controller:
      description: Name of controller to handle the event.
      example: "hallway"
    type:
      description: Type of the event.
      example: 'movement'
